apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blazor-unicorn-k8s
  labels:
    app.kubernetes.io/name: blazor-unicorn-k8s
    app.kubernetes.io/instance: blazor-unicorn
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx-public
    # The annotations below are required for my baremetal cluster
    # See: https://github.com/jetersen/home.cluster
    external-dns.alpha.kubernetes.io/target: public-ingress.jetersen.dev
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    # if your cluster is running in public cloud you can avoid using these.
spec:
  tls:
    - hosts:
        - "unicorn.jetersen.dev"
      secretName: unicorn.jetersen.dev-tls
  rules:
    - host: "unicorn.jetersen.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blazor-unicorn-k8s
                port:
                  name: http
